var config = require('./config')

let apiConfig;

apiConfig = {
  LOGIN : config.LOGIN,
  LOGOUT: config.LOGOUT,
  CHANGE_PWD: config.CHANGE_PWD,
  PROFILE: config.PROFILE,
  BIZ_PROFILE: config.BIZ_PROFILE,

  SYS_USER_SAVE:config.SYS_USER_SAVE,
  SYS_USER_LIST: config.SYS_USER_LIST,
  SYS_USER_DEL:config.SYS_USER_DEL,
  SYS_USER_INFO:config.SYS_USER_INFO,
  SYS_USER_EDIT:config.SYS_USER_EDIT,
  SYS_USER_BIND_ROLES:config.SYS_USER_BIND_ROLES,
  SYS_USER_ROLE_INFO:config.SYS_USER_ROLE_INFO,
  SYS_USER_RESET_PWD:config.SYS_USER_RESET_PWD,
  SYS_USER_RESET_PWD_LOIGN:config.SYS_USER_RESET_PWD_LOIGN,

  SYS_ROLE_LIST:config.SYS_ROLE_LIST,
  SYS_ROLE_INFO:config.SYS_ROLE_INFO,
  SYS_ROLE_SAVE:config.SYS_ROLE_SAVE,
  SYS_ROLE_DEL:config.SYS_ROLE_DEL,
  SYS_ROLE_MENU:config.SYS_ROLE_MENU,

  SYS_ROLE_BIND_MENU:config.SYS_ROLE_BIND_MENU,
  SYS_ROLE_MENU_BY_ID:config.SYS_ROLE_MENU_BY_ID,

  SYS_MENU_ALL:config.SYS_MENU_ALL,
  SYS_MENU_SAVE:config.SYS_MENU_SAVE,
  SYS_MENU_INFO:config.SYS_MENU_INFO,
  SYS_MENU_DEL:config.SYS_MENU_DEL,


  SYS_RESOURCE_LIST:config.SYS_RESOURCE_LIST,
  SYS_RESOURCE_SAVE:config.SYS_RESOURCE_SAVE,
  SYS_RESOURCE_DEL:config.SYS_RESOURCE_DEL,

  //system parameters - reference data
  SYS_PARAM_LIST:config.SYS_PARAM_LIST,
  SYS_PARAM_INFO:config.SYS_PARAM_INFO,
  SYS_PARAM_SAVE:config.SYS_PARAM_SAVE,
  SYS_PARAM_DEL:config.SYS_PARAM_DEL,
  SYS_PARAM_CATEGORY:config.SYS_PARAM_CATEGORY,

  CUS_CUSTOMER_LIST:config.CUS_CUSTOMER_LIST,
  CUS_CUSTOMER_SAVE:config.CUS_CUSTOMER_SAVE,
  CUS_CUSTOMER_DEL:config.CUS_CUSTOMER_DEL,
  CUS_CUSTOMER_INFO:config.CUS_CUSTOMER_INFO,
  CUS_CUSTOMER_MEMBER_SAVE:config.CUS_CUSTOMER_MEMBER_SAVE,

  CUS_CLOUDWARE_CUSTOMER_SELECTED:config.CUS_CLOUDWARE_CUSTOMER_SELECTED,
  CUS_CLOUDWARE_CUSTOMER_UNSELECTED:config.CUS_CLOUDWARE_CUSTOMER_UNSELECTED,
  CUS_CLOUDWARE_SAVE:config.CUS_CLOUDWARE_SAVE,
  CUS_CLOUDWARE_LIST:config.CUS_CLOUDWARE_LIST,
  CUS_CLOUDWARE_INFO:config.CUS_CLOUDWARE_INFO,
  CUS_CLOUDWARE_DEL:config.CUS_CLOUDWARE_DEL,
  CLOUDWARE_LIST:config.CLOUDWARE_LIST,
  CUS_WH_OWNER_LIST:config.CUS_WH_OWNER_LIST,

  CUSTOMER_WAREHOUSE_LIST:config.CUSTOMER_WAREHOUSE_LIST,

  CUS_WH_CUSTOMER_LIST:config.CUS_WH_CUSTOMER_LIST,
  CUS_AUTHWH_LIST:config.CUS_AUTHWH_LIST,
  CUS_WH_BIND_SAVE:config.CUS_WH_BIND_SAVE,
  CUS_WH_OWNER_LIST:config.CUS_WH_OWNER_LIST,
  CUS_WH_BIND_DEL:config.CUS_WH_BIND_DEL,

  BASE_ADDRESS_LIST:config.BASE_ADDRESS_LIST,
  BASE_ADDRESS_SAVE:config.BASE_ADDRESS_SAVE,
  BASE_ADDRESS_INFO:config.BASE_ADDRESS_INFO,
  BASE_ADDRESS_DEL:config.BASE_ADDRESS_DEL,

  BASE_RECEIVER_ADDRESS_LIST:config.BASE_RECEIVER_ADDRESS_LIST,
  LOG_WAYBILL_TRACE:config.LOG_WAYBILL_TRACE,
  LOG_WAYBILL_LIST:config.LOG_WAYBILL_LIST,
  LOG_PACKAGE_UPDATE:config.LOG_PACKAGE_UPDATE,
  LOG_WAYBILL_INFO:config.LOG_WAYBILL_INFO,
  LOG_WAYBILL_UPDATE:config.LOG_WAYBILL_UPDATE,
  LOG_PICKUP_LIST:config.LOG_PICKUP_LIST,
  LOG_PICKUP_SEND:config.LOG_PICKUP_SEND,
  LOG_WAYBILL_SEND:config.LOG_WAYBILL_SEND,
  LOG_PICKUP_CONFIRM:config.LOG_PICKUP_CONFIRM,
  LOG_WAYBILL_PRINT:config.LOG_WAYBILL_PRINT,
  LOG_WAYBILL_PDF:config.LOG_WAYBILL_PDF,
  LOG_STOCKOUT_DETAILS:config.LOG_STOCKOUT_DETAILS,


  ORDER_LIST:config.ORDER_LIST,
  ORDER_SAVE:config.ORDER_SAVE,
  ORDER_INFO:config.ORDER_INFO,
  ORDER_DEL:config.ORDER_DEL,
  ORDER_DETAILS_DISTRIBUTION_INFO:config.ORDER_DETAILS_DISTRIBUTION_INFO,

  WMS_MEDICINE_LIST:config.WMS_MEDICINE_LIST,
  WMS_COMMON:config.WMS_COMMON,

  SYS_MEMBER_LIST:config.SYS_MEMBER_LIST,
  SYS_MEMBER_SAVE:config.SYS_MEMBER_SAVE,
  SYS_MEMBER_DEL:config.SYS_MEMBER_DEL,
  SYS_MEMBER_ROLES:config.SYS_MEMBER_ROLES,
  SYS_MEMBER_ROLES_BIND:config.SYS_MEMBER_ROLES_BIND,
  SYS_MEMBER_COMMON:config.SYS_MEMBER_COMMON,

  DISTRIBUTION_LIST:config.DISTRIBUTION_LIST,
  DISTRIBUTION_SAVE:config.DISTRIBUTION_SAVE,
  DISTRIBUTION_INFO:config.DISTRIBUTION_INFO,
  ORDER_DISTRIBUTION_INFO:config.ORDER_DISTRIBUTION_INFO,
  DISTRIBUTION_DEL:config.DISTRIBUTION_DEL,

  STOCK_STOCK_LIST:config.STOCK_STOCK_LIST,
  STOCK_DISTRIBUTE_LIST:config.STOCK_DISTRIBUTE_LIST,
  STOCK_WAREHOUSE_LIST:config.STOCK_WAREHOUSE_LIST,
  STOCK_IO_STOCK_LIST:config.STOCK_IO_STOCK_LIST,
  STOCK_INOUT_DETAILS:config.STOCK_INOUT_DETAILS,

  B2B_LIST:config.B2B_LIST,
  B2B_SELECT_COMP_LIST:config.B2B_SELECT_COMP_LIST,
  B2B_BIND_CUS:config.B2B_BIND_CUS,
  B2B_INFO:config.B2B_INFO,

  WB_INVOICE_LIST:config.WB_INVOICE_LIST,
  WB_INVOICE_DEL:config.WB_INVOICE_DEL,
  WB_INVOICE_SAVE:config.WB_INVOICE_SAVE,

  LOG_LIST:config.LOG_LIST,
  LOG_SAVE:config.LOG_SAVE,
  LOG_DEL:config.LOG_DEL,

  STOCK_WAREHOUSE_LIST_CODE:config.STOCK_WAREHOUSE_LIST_CODE

}

export default apiConfig





