// 接口配置
// 服务器接口根地址
var config = require('../../config')
var isProduction = process.env.NODE_ENV === 'production'
var isUI = process.env.NODE_ENV === 'ui'
// 服务器地址
// export const SERVER_BASE_URL = isProduction ? 'http://gank.io' : 'www.baidu.com'
const SERVER_BASE_URL = isProduction ? config.build.baseServerUrl : config.dev.baseServerUrl

const SYS_USER_API_COMMOM = '/v1/user/';
const SYS_ROLE_API_COMMOM = '/v1/role/';
const SYS_MENU_API_COMMOM = '/v1/menu/';
const SYS_RESOURECE_API_COMMOM = '/v1/resource/'
const SYS_ROLE_MENU_COMMON = '/v1/roleMenu/'
const SYS_PARAM_COMMON = SERVER_BASE_URL+'/v1/referenceData/'
const CUS_CUSTOMER_COMMON = SERVER_BASE_URL + '/v1/customer/'
const CUS_CLOUDWARE_COMMON = SERVER_BASE_URL + '/v1/wareHouse/'
const CUS_WH_REF_COMMON = SERVER_BASE_URL + '/v1/customerWareHouseRel/'

const BASE_ADDRESS_COMMON = SERVER_BASE_URL+'/v1/address/'
const LOG_LOGISTICS_COMMOM = SERVER_BASE_URL+'/v1/LOG/'
const LOG_EXPRESS_COMMOM = SERVER_BASE_URL+'/express/'
const LOG_PICKUP_COMMOM = SERVER_BASE_URL+'/v1/pickupInfo/'
const ORDER_COMMON = SERVER_BASE_URL+'/v1/order/'
const ORDER_DISTRIBUTION = SERVER_BASE_URL+'/v1/orderDistribution/'
const ORDER_DISTRIBUTION_DETAIL = SERVER_BASE_URL+'/v1/orderDistributionDetails/'
const WMS_COMMON = SERVER_BASE_URL+'/v1/wms/'
const SYS_MEMBER_COMMON = SERVER_BASE_URL + '/v1/member/'
const SYS_OWNER_COMMON = SERVER_BASE_URL + '/v1/tpOwner/'
const STOCK_COMMON = SERVER_BASE_URL + "/v1/tpGoods/"
const STOCK_IO_COMMON = SERVER_BASE_URL + "/v1/orderDistribution/"
const B2B_COMMON = SERVER_BASE_URL + "/v1/cWUserRequestDTLS/"
const INVOICE_COMMON = SERVER_BASE_URL + "/v1/pickupInfo/"
const WMS_STOCK_INOUT_COMMON = SERVER_BASE_URL + "/v1/cWInOutStockDetail/"

let
  LOGIN ,
  LOGOUT,
  CHANGE_PWD,
  PROFILE ,BIZ_PROFILE,
  SYS_USER_LIST, SYS_USER_SAVE, SYS_USER_DEL, SYS_USER_INFO,SYS_USER_BIND_ROLES,SYS_USER_ROLE_INFO,SYS_USER_RESET_PWD,SYS_USER_RESET_PWD_LOIGN,
  SYS_ROLE_LIST, SYS_ROLE_SAVE, SYS_ROLE_INFO, SYS_ROLE_DEL,SYS_ROLE_MENU,
  SYS_ROLE_BIND_MENU,SYS_ROLE_MENU_BY_ID,
  SYS_MENU_ALL, SYS_MENU_SAVE, SYS_MENU_INFO, SYS_MENU_DEL,
  SYS_RESOURCE_LIST,SYS_RESOURCE_SAVE,SYS_RESOURCE_DEL,
  SYS_PARAM_LIST , SYS_PARAM_SAVE , SYS_PARAM_INFO , SYS_PARAM_DEL, SYS_PARAM_CATEGORY,
  BASE_ADDRESS_LIST , BASE_ADDRESS_SAVE , BASE_ADDRESS_INFO , BASE_ADDRESS_DEL,BASE_RECEIVER_ADDRESS_LIST,
  CUS_CUSTOMER_LIST,CUS_CUSTOMER_SAVE,CUS_CUSTOMER_DEL,CUS_CUSTOMER_INFO,CUS_CUSTOMER_MEMBER_SAVE,
  CUS_CLOUDWARE_CUSTOMER_SELECTED,CUS_CLOUDWARE_CUSTOMER_UNSELECTED,CUS_CLOUDWARE_SAVE,CUS_CLOUDWARE_LIST,CUS_CLOUDWARE_DEL,CUS_WH_CUSTOMER_LIST,CLOUDWARE_LIST,CUS_CLOUDWARE_INFO,CUS_WH_BIND_DEL,
  CUS_AUTHWH_LIST,CUS_WH_BIND_SAVE,LOG_WAYBILL_TRACE,LOG_WAYBILL_LIST,LOG_PACKAGE_UPDATE,LOG_WAYBILL_INFO,LOG_WAYBILL_UPDATE,
  LOG_PICKUP_LIST,LOG_PICKUP_SEND,LOG_WAYBILL_SEND,LOG_PICKUP_CONFIRM,LOG_WAYBILL_PRINT,LOG_STOCKOUT_DETAILS,LOG_WAYBILL_PDF,
  ORDER_LIST,ORDER_SAVE,ORDER_INFO,ORDER_DEL,ORDER_DETAILS_DISTRIBUTION_INFO,
  WMS_MEDICINE_LIST,CUS_WH_OWNER_LIST,CUSTOMER_WAREHOUSE_LIST,
  SYS_MEMBER_LIST,SYS_MEMBER_SAVE,SYS_MEMBER_DEL,SYS_MEMBER_ROLES,SYS_MEMBER_ROLES_BIND,
  DISTRIBUTION_LIST,DISTRIBUTION_SAVE,DISTRIBUTION_INFO,DISTRIBUTION_DEL,ORDER_DISTRIBUTION_INFO,
  STOCK_STOCK_LIST,STOCK_DISTRIBUTE_LIST,STOCK_WAREHOUSE_LIST,STOCK_IO_STOCK_LIST,STOCK_INOUT_DETAILS,
  B2B_LIST,B2B_SELECT_COMP_LIST,B2B_BIND_CUS,B2B_INFO,
  WB_INVOICE_LIST,WB_INVOICE_DEL,WB_INVOICE_SAVE,
  LOG_LIST,LOG_SAVE,LOG_DEL,
  STOCK_WAREHOUSE_LIST_CODE;


if( isUI ){
  LOGIN = SERVER_BASE_URL + '/login.json';
  LOGOUT = SERVER_BASE_URL + '/logout.json';
  CHANGE_PWD = SERVER_BASE_URL + '/changePwd';
  PROFILE = SERVER_BASE_URL + '/profile.json';
  BIZ_PROFILE = SERVER_BASE_URL + '/bizprofile.json';
  SYS_USER_LIST = SERVER_BASE_URL + '/userlist.json';
  SYS_USER_SAVE = SERVER_BASE_URL + '/userAdd.json';
  SYS_USER_DEL = SERVER_BASE_URL + '/userDel.json';
  SYS_USER_INFO = SERVER_BASE_URL + '/userInfo.json';
  SYS_USER_RESET_PWD = SERVER_BASE_URL + '/v1/reset/pwd.json';

  SYS_ROLE_LIST = SERVER_BASE_URL + '/roleList.json';
  SYS_ROLE_SAVE  = SERVER_BASE_URL + '/roleSave.json';
  SYS_ROLE_INFO = SERVER_BASE_URL + '/roleInfo.json';
  SYS_ROLE_DEL  = SERVER_BASE_URL + '/roleDel.json';
  SYS_RESOURCE_SAVE = SERVER_BASE_URL + '/resourceSave.json';

  SYS_PARAM_LIST = SYS_PARAM_COMMON + "referenceDatalist.json";
  SYS_PARAM_SAVE  = SYS_PARAM_COMMON+".json";
  SYS_PARAM_INFO = SYS_PARAM_COMMON+".json";
  SYS_PARAM_DEL  = SYS_PARAM_COMMON+".json";
  SYS_PARAM_CATEGORY = SYS_PARAM_COMMON + "category/category.json";

  SYS_ADDRESS_LIST = BASE_ADDRESS_COMMON + "addresslist.json";
  SYS_ADDRESS_SAVE  = BASE_ADDRESS_COMMON+".json";
  SYS_ADDRESS_INFO = BASE_ADDRESS_COMMON+".json";
  SYS_ADDRESS_DEL  = BASE_ADDRESS_COMMON+".json";
  BASE_RECEIVER_ADDRESS_LIST = BASE_ADDRESS_COMMON+"receiverAddresslist.json";

  LOG_WAYBILL_TRACE = LOG_LOGISTICS_COMMOM + "traceWaybill.json";
  LOG_WAYBILL_LIST = LOG_LOGISTICS_COMMOM + "getWaybillList.json";
  LOG_PACKAGE_UPDATE = LOG_LOGISTICS_COMMOM + "packageUpdate.json";
  LOG_WAYBILL_INFO = LOG_LOGISTICS_COMMOM + "getWaybillInfo.json";
  LOG_WAYBILL_UPDATE = LOG_LOGISTICS_COMMOM + "updateWaybillInfo.json";
  LOG_PICKUP_LIST = LOG_PICKUP_COMMOM + "pickupInfolist.json";
  LOG_PICKUP_SEND = LOG_LOGISTICS_COMMOM + "waybillPickUp.json";
  LOG_WAYBILL_SEND = LOG_LOGISTICS_COMMOM + "sendWaybill.json";
  LOG_PICKUP_CONFIRM = LOG_LOGISTICS_COMMOM + "confirmPickUp.json";
  LOG_WAYBILL_PRINT = LOG_LOGISTICS_COMMOM + "waybillPrint.json";
  LOG_WAYBILL_PDF = LOG_EXPRESS_COMMOM + "generatePdf.json";
  LOG_STOCKOUT_DETAILS = LOG_LOGISTICS_COMMOM + "getStockOutDetails.json";
  STOCK_INOUT_DETAILS = WMS_STOCK_INOUT_COMMON + "stockInOutDetaillist.json";

  ORDER_LIST = ORDER_COMMON + "orderlist.json";
  ORDER_SAVE = ORDER_COMMON+".json";
  ORDER_INFO = ORDER_COMMON+".json";
  ORDER_DEL = ORDER_COMMON+".json";
  ORDER_DETAILS_DISTRIBUTION_INFO = ORDER_COMMON+"/distribution.json";

  WMS_MEDICINE_LIST = WMS_COMMON+".json"

}else{
  LOGIN = SERVER_BASE_URL + '/login';
  LOGOUT = SERVER_BASE_URL + '/logout';
  CHANGE_PWD = SERVER_BASE_URL + '/changePwd';
  PROFILE = SERVER_BASE_URL + '/v1/profile';
  BIZ_PROFILE = SERVER_BASE_URL + '/v1/profile/biz';
  SYS_USER_LIST = SERVER_BASE_URL + '/v1/userlist';
  SYS_USER_SAVE  = SERVER_BASE_URL + SYS_USER_API_COMMOM;
  SYS_USER_DEL  = SERVER_BASE_URL + SYS_USER_API_COMMOM;
  SYS_USER_INFO = SERVER_BASE_URL + SYS_USER_API_COMMOM;
  SYS_USER_BIND_ROLES = SERVER_BASE_URL + SYS_USER_API_COMMOM;
  SYS_USER_ROLE_INFO  = SERVER_BASE_URL + SYS_USER_API_COMMOM;
  SYS_USER_RESET_PWD  = SERVER_BASE_URL + "/v1/reset/pwd";
  SYS_USER_RESET_PWD_LOIGN  = SERVER_BASE_URL + "/v1/user/changePws";

  SYS_ROLE_LIST = SERVER_BASE_URL + "/v1/rolelist/";
  SYS_ROLE_SAVE  = SERVER_BASE_URL + SYS_ROLE_API_COMMOM;
  SYS_ROLE_INFO = SERVER_BASE_URL + SYS_ROLE_API_COMMOM;
  SYS_ROLE_DEL  = SERVER_BASE_URL + SYS_ROLE_API_COMMOM;
  SYS_ROLE_MENU = SERVER_BASE_URL + SYS_ROLE_API_COMMOM;

  SYS_ROLE_BIND_MENU  = SERVER_BASE_URL + '/v1/roleMenus/';
  SYS_ROLE_MENU_BY_ID = SERVER_BASE_URL + SYS_ROLE_MENU_COMMON;

  SYS_MENU_ALL = SERVER_BASE_URL + "/v1/menu/all";
  SYS_MENU_SAVE  = SERVER_BASE_URL + SYS_MENU_API_COMMOM;
  SYS_MENU_INFO = SERVER_BASE_URL + SYS_MENU_API_COMMOM;
  SYS_MENU_DEL  = SERVER_BASE_URL + SYS_MENU_API_COMMOM;

  SYS_RESOURCE_LIST = SERVER_BASE_URL + SYS_RESOURECE_API_COMMOM;
  SYS_RESOURCE_SAVE = SERVER_BASE_URL + SYS_RESOURECE_API_COMMOM;
  SYS_RESOURCE_DEL  = SERVER_BASE_URL + SYS_RESOURECE_API_COMMOM;

  SYS_PARAM_LIST = SYS_PARAM_COMMON + "referenceDatalist";
  SYS_PARAM_SAVE  = SYS_PARAM_COMMON;
  SYS_PARAM_INFO = SYS_PARAM_COMMON;
  SYS_PARAM_DEL  = SYS_PARAM_COMMON;
  SYS_PARAM_CATEGORY = SYS_PARAM_COMMON + "category/";

  CUS_CUSTOMER_LIST = CUS_CUSTOMER_COMMON + "customerlist";
  CUS_CUSTOMER_SAVE = CUS_CUSTOMER_COMMON;
  CUS_CUSTOMER_DEL  = CUS_CUSTOMER_COMMON + "delete";
  CUS_CUSTOMER_INFO = CUS_CUSTOMER_COMMON;
  CUS_CUSTOMER_MEMBER_SAVE = CUS_CUSTOMER_COMMON +  "member";

  CUS_CLOUDWARE_CUSTOMER_SELECTED   = CUS_CLOUDWARE_COMMON+"selectedCustomerList";
  CUS_CLOUDWARE_CUSTOMER_UNSELECTED   = CUS_CLOUDWARE_COMMON+"unselectedCustomerList";
  CUS_CLOUDWARE_SAVE   = CUS_CLOUDWARE_COMMON;
  CUS_CLOUDWARE_LIST   = CUS_CLOUDWARE_COMMON + "wareHouselist";
  CUS_CLOUDWARE_INFO   = CUS_CLOUDWARE_COMMON;
  CLOUDWARE_LIST   = CUS_CLOUDWARE_COMMON + "cloudwarehouseList";
  CUS_CLOUDWARE_DEL    = CUS_CLOUDWARE_COMMON;
  CUS_WH_CUSTOMER_LIST = CUS_CLOUDWARE_COMMON + "customerList";
  CUS_WH_OWNER_LIST = SYS_OWNER_COMMON + "tpOwnerlist";
  CUS_WH_BIND_DEL = CUS_WH_REF_COMMON + "del";

  CUSTOMER_WAREHOUSE_LIST = CUS_WH_REF_COMMON + "customerWareHouseRellist";

  BASE_ADDRESS_LIST = BASE_ADDRESS_COMMON + "addresslist";
  BASE_ADDRESS_SAVE  = BASE_ADDRESS_COMMON;
  BASE_ADDRESS_INFO = BASE_ADDRESS_COMMON;
  BASE_ADDRESS_DEL  = BASE_ADDRESS_COMMON;
  BASE_RECEIVER_ADDRESS_LIST = BASE_ADDRESS_COMMON + "receiverAddresslist";


  CUS_AUTHWH_LIST      = CUS_CLOUDWARE_COMMON + "wareHouselist";
  CUS_WH_BIND_SAVE     = CUS_WH_REF_COMMON;

  LOG_WAYBILL_TRACE = LOG_LOGISTICS_COMMOM + "traceWaybill.json";
  LOG_WAYBILL_LIST = LOG_LOGISTICS_COMMOM + "getWaybillList.json";
  LOG_PACKAGE_UPDATE = LOG_LOGISTICS_COMMOM + "packageUpdate.json";
  LOG_WAYBILL_INFO = LOG_LOGISTICS_COMMOM + "getWaybillInfo.json";
  LOG_WAYBILL_UPDATE = LOG_LOGISTICS_COMMOM + "updateWaybillInfo.json";
  LOG_PICKUP_LIST = LOG_PICKUP_COMMOM + "pickupInfolist.json";
  LOG_PICKUP_SEND = LOG_LOGISTICS_COMMOM + "waybillPickUp.json";
  LOG_WAYBILL_SEND = LOG_LOGISTICS_COMMOM + "sendWaybill.json";
  LOG_PICKUP_CONFIRM = LOG_LOGISTICS_COMMOM + "confirmPickUp.json";
  LOG_WAYBILL_PRINT = LOG_LOGISTICS_COMMOM + "waybillPrint.json";
  LOG_WAYBILL_PDF = LOG_EXPRESS_COMMOM + "generatePdf.json";
  LOG_STOCKOUT_DETAILS = LOG_LOGISTICS_COMMOM + "getStockOutDetails.json";
  STOCK_INOUT_DETAILS = WMS_STOCK_INOUT_COMMON + "stockInOutDetaillist.json";

  ORDER_LIST = ORDER_COMMON + "orderlist";
  ORDER_SAVE = ORDER_COMMON;
  ORDER_INFO = ORDER_COMMON;
  ORDER_DEL = ORDER_COMMON;
  ORDER_DETAILS_DISTRIBUTION_INFO = ORDER_COMMON;

  DISTRIBUTION_LIST = ORDER_DISTRIBUTION + "orderDistributionlist";
  DISTRIBUTION_SAVE = ORDER_DISTRIBUTION;
  DISTRIBUTION_INFO = ORDER_DISTRIBUTION;
  DISTRIBUTION_DEL = ORDER_DISTRIBUTION;
  ORDER_DISTRIBUTION_INFO = ORDER_DISTRIBUTION+"order/";

  WMS_MEDICINE_LIST = WMS_COMMON+"medicineList";
  SYS_MEMBER_LIST = SYS_MEMBER_COMMON + "memberlist";
  SYS_MEMBER_SAVE = SYS_MEMBER_COMMON;
  SYS_MEMBER_DEL = SYS_MEMBER_COMMON + "delete";
  SYS_MEMBER_ROLES = SYS_MEMBER_COMMON + "roles";
  SYS_MEMBER_ROLES_BIND = SYS_MEMBER_COMMON + "rolesBind";

  STOCK_STOCK_LIST = STOCK_COMMON + "tpGoodslist";
  STOCK_DISTRIBUTE_LIST = ORDER_DISTRIBUTION_DETAIL + "list";
  STOCK_WAREHOUSE_LIST = CUS_CLOUDWARE_COMMON + "cloudwarehouseList";
  STOCK_WAREHOUSE_LIST_CODE = CUS_CLOUDWARE_COMMON + "cloudwarehouseListByCode";

  STOCK_IO_STOCK_LIST = STOCK_IO_COMMON + "orderDistributionlist";

  B2B_LIST = B2B_COMMON + "cWUserRequestDTLSlist";
  B2B_SELECT_COMP_LIST = B2B_COMMON + "selectCompList";
  B2B_BIND_CUS = B2B_COMMON + "bindCus";
  B2B_INFO = B2B_COMMON;




  WB_INVOICE_LIST = INVOICE_COMMON + "pickupInfolistPage";
  WB_INVOICE_DEL = INVOICE_COMMON ;
  WB_INVOICE_SAVE = INVOICE_COMMON ;

  LOG_LIST = LOG_LOGISTICS_COMMOM + "logisticsList";
  LOG_SAVE = LOG_LOGISTICS_COMMOM + "logistics";
  LOG_DEL  = LOG_LOGISTICS_COMMOM + "logistics/";
}

export {
  LOGIN , LOGOUT,CHANGE_PWD,PROFILE,BIZ_PROFILE,
  SYS_USER_LIST,SYS_USER_SAVE,SYS_USER_DEL,SYS_USER_INFO,SYS_USER_BIND_ROLES,SYS_USER_ROLE_INFO,SYS_USER_RESET_PWD,SYS_USER_RESET_PWD_LOIGN,
  SYS_ROLE_LIST,SYS_ROLE_SAVE,SYS_ROLE_INFO,SYS_ROLE_DEL,
  SYS_ROLE_BIND_MENU,SYS_ROLE_MENU_BY_ID,
  SYS_MENU_ALL, SYS_MENU_SAVE, SYS_MENU_INFO, SYS_MENU_DEL,
  SYS_RESOURCE_LIST,SYS_RESOURCE_SAVE,SYS_RESOURCE_DEL,SYS_ROLE_MENU,
  SYS_PARAM_LIST , SYS_PARAM_SAVE , SYS_PARAM_INFO , SYS_PARAM_DEL , SYS_PARAM_CATEGORY,
  BASE_ADDRESS_LIST , BASE_ADDRESS_SAVE , BASE_ADDRESS_INFO , BASE_ADDRESS_DEL,BASE_RECEIVER_ADDRESS_LIST,
  CUS_CUSTOMER_LIST,CUS_CUSTOMER_SAVE,CUS_CUSTOMER_DEL,CUS_CUSTOMER_INFO,CUS_CUSTOMER_MEMBER_SAVE,
  CUS_CLOUDWARE_CUSTOMER_SELECTED,CUS_CLOUDWARE_CUSTOMER_UNSELECTED,CUS_CLOUDWARE_SAVE,CUS_CLOUDWARE_LIST,CUS_CLOUDWARE_DEL,CUS_WH_CUSTOMER_LIST,CLOUDWARE_LIST,CUS_CLOUDWARE_INFO,CUS_WH_OWNER_LIST,CUS_WH_BIND_DEL,
  CUS_AUTHWH_LIST,CUS_WH_BIND_SAVE,LOG_WAYBILL_TRACE,LOG_WAYBILL_LIST,LOG_PACKAGE_UPDATE,LOG_WAYBILL_INFO,LOG_WAYBILL_UPDATE,
  LOG_PICKUP_LIST,LOG_PICKUP_SEND,LOG_WAYBILL_SEND,LOG_PICKUP_CONFIRM,LOG_WAYBILL_PRINT,LOG_STOCKOUT_DETAILS,LOG_WAYBILL_PDF,
  ORDER_LIST, ORDER_SAVE, ORDER_INFO, ORDER_DEL,ORDER_DETAILS_DISTRIBUTION_INFO,
  WMS_COMMON,WMS_MEDICINE_LIST,CUSTOMER_WAREHOUSE_LIST,
  SYS_MEMBER_LIST,SYS_MEMBER_SAVE,SYS_MEMBER_DEL,SYS_MEMBER_ROLES,SYS_MEMBER_ROLES_BIND,SYS_MEMBER_COMMON,
  DISTRIBUTION_LIST,DISTRIBUTION_SAVE,DISTRIBUTION_INFO,DISTRIBUTION_DEL,ORDER_DISTRIBUTION_INFO,
  STOCK_STOCK_LIST,STOCK_DISTRIBUTE_LIST,STOCK_WAREHOUSE_LIST,STOCK_IO_STOCK_LIST,STOCK_INOUT_DETAILS,
  B2B_LIST,B2B_SELECT_COMP_LIST,B2B_BIND_CUS,B2B_INFO,
  WB_INVOICE_LIST,WB_INVOICE_DEL,WB_INVOICE_SAVE,LOG_LIST,LOG_SAVE,LOG_DEL,STOCK_WAREHOUSE_LIST_CODE
}


